version: '3'
services:
  app:
    container_name: s3proxy
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - . :/usr/src/app/.
    environment:
        - BUCKET=somebucket
